FROM python:3.11.6-slim-bullseye

# Install apt packages
RUN apt-get update && apt-get install --no-install-recommends -y \
  # dependencies for building Python packages
  build-essential \
  # psycopg2 dependencies
  libpq-dev \
  # cleaning up unused files
  && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
  && rm -rf /var/lib/apt/lists/*


# Install dependencies
COPY ./requirements ./requirements
RUN pip install --upgrade pip
RUN pip install -r requirements/local.txt

# Set environment variables
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

# Set work directory
WORKDIR /app

COPY ./docker/local/django/entrypoint /entrypoint
RUN chmod +x /entrypoint

COPY ./docker/local/django/start /start
RUN chmod +x /start

COPY . .

EXPOSE 8000

ENTRYPOINT ["/entrypoint"]

CMD ["/start"]
